INSERT INTO produit (ID, NUMERO_PRODUIT, LIBELLE) VALUES (1000, 10, 'Ultimate');
INSERT INTO produit (ID, NUMERO_PRODUIT, LIBELLE) VALUES (2000, 20, 'Serenite');
INSERT INTO produit (ID, NUMERO_PRODUIT, LIBELLE) VALUES (3000, 30, 'Kinder');
INSERT INTO produit (ID, NUMERO_PRODUIT, LIBELLE) VALUES (11, 40, 'Cocotte');
INSERT INTO produit (ID, NUMERO_PRODUIT, LIBELLE) VALUES (12, 50, 'Les patates');
INSERT INTO produit (ID, NUMERO_PRODUIT, LIBELLE) VALUES (10, 60, 'Tofu');